name: Test

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  linux:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os:
          - debian:testing
    container:
      image: ${{ matrix.os }}
      options: --privileged
      env:
        CI: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install deps
        run: SKIP_OPENSSL3=1 sh .ci/deps.sh

      - name: Assign name for test results artifact
        run: echo ARTIFACT="$(echo '${{ matrix.os }}' | sed 's|[:/]|_|g')" >>"$GITHUB_ENV"

      - name: Create a non-privileged user
        run: sh .ci/test/prepare.sh

      - name: Run tests with default settings
        run: sudo -u build CI=1 sh .ci/test/run.sh default
        if: always()

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: always()

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: tests_${{ env.ARTIFACT }}
          path: /tmp/logs/tests.*.tar.gz
        if: always()

      - name: Build package
        run: sh .ci/package/build.sh
        if: github.ref == 'refs/heads/1.1' || startsWith(github.ref, 'refs/tags/release-')
        continue-on-error: true

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: pkg-${{ env.ARTIFACT }}
          path: |
            *.deb
            ~/rpmbuild/RPMS/*/*.rpm
        continue-on-error: true
