name: Build and test

on:
  push:
    branches:
      - master
      - "1.1"
    tags:
      - "release-*"

  pull_request:
    types:
      - opened
      - synchronize

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Artistic Style
        run: sudo apt-get install -y astyle

      - name: Check code formatting
        run: |
          shopt -s globstar
          ! astyle --options=.astylerc --dry-run --formatted ./**/*.[ch] | grep '^Formatted'

  linux:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        compiler: [clang, gcc]
        legacy_protocol: ["", --disable-legacy-protocol]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.compiler }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install build deps
        run: >
          sudo apt-get install -y --no-install-{recommends,suggests}
          zlib1g-dev
          liblzo2-dev
          libncurses-dev
          libreadline-dev
          libminiupnpc-dev
          libvdeplug-dev
          netcat

      - name: Install OpenSSL
        run: sudo apt-get install -y libssl-dev
        if: ${{ matrix.legacy_protocol == '' }}

      - name: Run autoreconf
        run: autoreconf -fsi

      - name: Run ./configure
        run: >
          ./configure 
          --enable-{miniupnpc,uml,vde}
          ${{ matrix.legacy_protocol }}

      - name: Compile project
        run: make -j$(nproc)

      - name: Run tests
        # root is required for some tests
        run: sudo make check-recursive VERBOSE=1
        timeout-minutes: 20

      - name: Archive test results
        run: sudo tar -caf test-results.tar.gz test/*.log test/*.test.*/
        if: always()

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: tests_${{ matrix.os }}_${{ matrix.compiler }}
          path: test-results.tar.gz
        if: always()

  windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install msys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          # https://packages.msys2.org/package/
          install: >-
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-openssl
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-lzo2
            mingw-w64-x86_64-ncurses
            mingw-w64-x86_64-miniupnpc
            git

      - name: Build the project
        shell: msys2 {0}
        run: |
          autoreconf -fsi
          ./configure --with-curses-include=/mingw64/include/ncurses --disable-readline
          make -j$(nproc)

      - name: Check that tinc can be started
        shell: msys2 {0}
        run: ./src/tinc --version

      - name: Check that tincd can be started
        shell: msys2 {0}
        run: ./src/tincd --version

  deb-build:
    if: startsWith(github.ref, 'refs/tags/release-')
    needs: linux

    strategy:
      matrix:
        os: ["ubuntu-18.04", ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install build deps
        run: >
          sudo apt-get install -y --no-install-{recommends,suggests}
          devscripts
          git-buildpackage
          dh-make
          texinfo
          libssl-dev
          zlib1g-dev
          liblzo2-dev
          libncurses-dev
          libreadline-dev

      - name: Run autoreconf
        run: autoreconf -fsi

      - name: Prepare debian directory
        run: bash .github/workflows/deb/prepare

      - name: Build deb package
        run: dpkg-buildpackage -d -us -uc

      - name: Upload packages
        uses: actions/upload-artifact@v2
        with:
          name: deb-package-${{ matrix.os }}
          path: "*.deb"

  deb-publish:
    needs: deb-build

    strategy:
      matrix:
        os: ["ubuntu-18.04", ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Download built packages
        uses: actions/download-artifact@v2
        with:
          name: deb-package-${{ matrix.os }}

      - name: Install package
        run: apt install -y ./*.deb

      - name: Prepare tinc configs
        run: |
          set -eu
          sudo mkdir -p /etc/tinc/test/hosts
          sudo tinc -b -n test generate-ed25519-keys
          echo "Name test" | sudo tee /etc/tinc/test/tinc.conf

      - name: Enable and start tincd
        run: |
          sudo systemctl start tinc@test
          sudo tinc -n test dump reachable nodes

      - name: Publish deb package
        uses: softprops/action-gh-release@v1
        with:
          files: "*.deb"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos:
    runs-on: macos-10.15

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: brew install coreutils netcat automake lzo miniupnpc

      - name: Run autoreconf
        run: autoreconf -fsi

      - name: Run ./configure
        run: >
          ./configure
          --with-openssl=/usr/local/opt/openssl@1.1
          --enable-{tunemu,miniupnpc}

      - name: Compile application
        run: make -j$(sysctl -n hw.ncpu)

      - name: Run tests
        run: make check-recursive VERBOSE=1
        timeout-minutes: 20

      - name: Archive test results
        run: sudo tar -caf test-results.tar.gz test/*.log test/*.test.*/
        if: always()

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: tests_${{ runner.os }}
          path: test-results.tar.gz
        if: always()
